### ISSUE TITLE
Profiling Edge Browser

### ISSUE THREAD

**Issue by Alois-xx** [RudjiGames/MTuner#107]
I just want to try out MTuner. 
I have drag and dropped msedge.exe to MTuner

- "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"

Is there a way to attach to an already running process and what about applications which spawn child processes like browsers. 
I guess that is not supported? 

![grafik](https://github.com/RudjiGames/MTuner/assets/408821/143d2a7f-7322-44c7-83cf-15fd47e538da)

![grafik](https://github.com/RudjiGames/MTuner/assets/408821/d2eb3d57-7ebf-494d-ba4f-b35445a00b23)

https://msdl.microsoft.com/download/symbols
C:\Users\akrau\AppData\Roaming\MTuner\Symbols

I have used the https endpoint. I am not sure if MTuner even tries to load symbols from the old location I have previously configured: 

![grafik](https://github.com/RudjiGames/MTuner/assets/408821/aa29342e-9e41-4786-ad0e-13798e195cd4)

Is there any reload/refresh symbol button in the UI? When I retry again with a fresh MTuner instance 

![grafik](https://github.com/RudjiGames/MTuner/assets/408821/c7703314-1156-4178-af3a-f69f6f71306c)

I still get only partial stacks and some locations not located in any module. Not sure if that is due to Javascript or if that is an issue here.

**Comment by milostosic** [comment]
Attaching to running process is not supported.
There were fixes for debug symbols since you opened this issue, closing for now.
