### ISSUE TITLE
file may be corrupted

### ISSUE THREAD

**Issue by gjaegy** [RudjiGames/MTuner#111]
Hi Milos,

I hope you are well.

I'm using MTuner again, but I'm facing some random issues, where the capture file gets sometimes corrupted (and sometimes not).

I've uploaded the capture file (it seems two files are always created).

http://www.imagine3d.fr/_temp/MTuner.rar

I'm using the latest 4.8 version of MTuner.

Any idea what's causing that ?

thanks a lot !

**Comment by milostosic** [comment]
Hello, I'm off to vacation today - let's revisit this in ~2 weeks.

**Comment by gjaegy** [comment]
Thanks for your prompt answer, enjoy your time off then !

**Comment by gjaegy** [comment]
After some furhter investigations, it seems the issue is likely due to a concurrency issue.

We compile our shaders using multiple threads. With the original code (multiple threads), the capture file is corrupted most of the time (5-10% of the times it's not), and I have some false positive memory leaks.

When compiling the shaders in a single thread, the corruption doesn't occur, as the false positives.

**Comment by milostosic** [comment]
Thanks! It's been a long time suspicion that there's a threading issue which would almost certainly be in [rmem](https://github.com/RudjiGames/rmem) project if you'd like to chase this further while I'm away

**Comment by gjaegy** [comment]
I'm afraid I won't have enough time, I'll be on vacation starting from tomorrow and hence have to complete a few things before I leave :/

**Comment by milostosic** [comment]
A number of bugs have been fixed, could you please give this another go?

**Comment by gjaegy** [comment]
Just trying the latest release, it seems CityHash is missing, I thought I would simply use the standard version, but you declare the function in the "rmem" namespace ? missing file maybe ?

**Comment by milostosic** [comment]
sorry, possible I've missed it, you can grab the latest directly from [here](https://github.com/RudjiGames/rmem). File is definitely [there](https://github.com/RudjiGames/rmem/blob/master/src/rmem_hash.cpp)

**Comment by gjaegy** [comment]
perfect thank you !

**Comment by gjaegy** [comment]
Hi Milos,

I'm currently spending some time doing a mem leaks check session, and it seems MTuner properly handles my threads, no more corrupted capture file, so thanks for that !!

One remaining issue I have, not very important, but I thought I would mention it: MTuner seems to be unable to resolve module/function for a DLL (actually file extension is .dlg, but it's a .dll) that is being loaded dynamically (that's ImagineIG.dlg), see screenshot:

![image](https://github.com/user-attachments/assets/b5390a7b-d469-4670-a0b3-1d7f26c21c71)

I'm happy to help !

**Comment by milostosic** [comment]
Can you please open another issue for the dll/dlg problem? I do have some thoughts why that may be.
Thanks for confirming the corruption is resolved!
