### ISSUE TITLE
Expectations for PDB file next to .exe.

### ISSUE THREAD

**Issue by gammak** [RudjiGames/MTuner#112]
Hi there, I'm looking to use MTuner to profile a local binary and the feature set and ease-of-use look great!

One issue I'm running into is that I'm not quite sure how to get MTuner to load the PDB that sits next to the .exe file. I'm sure this is something I'm doing wrong, but I'd love to just get clarity on what the requirements/expectations for loading local PDBs are.

I've tried the following, but symbols never load:
* Loading the .exe as-is with no symbol server
* Setting the symbol server path to the directory containing the exe
* The the local symbol cache path to the directory containing the exe.

I notice that when running `symchk` on the exe, it says that the PDB has an age mismatch (since the PDB and exe are generated at two different build steps). Would this potentially be relevant (and if so, any way around that?)

Is the expectation that just drag-and-dropping an exe into MTuner should have symbols if there's a PDB with the same name next to it (even without setting a symbol server?) Or is there an expectation that I should locally host a Symbol Store?

Any tips would be greatly appreciated here, even if they're just to say that my expectations are wrong.

**Comment by gammak** [comment]
Even after modifying the PDB to avoid the age mismatch and pass `symchk .\my_app.exe /s .`, still seeing the same thing (haven't modified any symbol path data beyond the above though).

**Comment by milostosic** [comment]
Hi, the symbols are automatically loaded when drag and dropping an executable. Related code is in rdebug project. It's not super robust and I've seen reports of it failing similar to what you describe but I haven't had a repro case to try and figure this out. There are better PDB parsers now so this code is overdue for an update but that's very low on my priority list... :/

**Comment by milostosic** [comment]
4.8.1 will now try to load PDB file with the same name as exe/dll, if located in the same directory. Mind giving this a try?

**Comment by milostosic** [comment]
More fixes in 4.8.3, closing for now.
