### ISSUE TITLE
Outdated documentation link in MTuner 

### ISSUE THREAD

**Issue by jsjtxietian** [RudjiGames/MTuner#113]
Thanks for the great work!

I found the following link is outdated: 

https://github.com/RudjiGames/MTuner/blob/0b26438599b6aeddd1eaa4f86eb2174702caa603/src/MTuner/src/mtuner.cpp#L377

I suppose the correct one is the one linked in readme: https://rudjigames.github.io/MTuner/

Let me know if I can help make a pr.

**Comment by milostosic** [comment]
Fixed, thanks for noticing this!

**Comment by Erik-Schulz** [comment]
The latest release for Windows contains `Trojan:Win32/Bearfoos.B!ml` and was blocked by my local copy of Windows Defender.
