### ISSUE TITLE
Symbol Paths Not Respected?

### ISSUE THREAD

**Issue by forrestsmithfb** [RudjiGames/MTuner#97]
I'm having a lot of difficulties with symbol server support.

1. It looks like the checkbox for `_NT_SYMBOL_PATH` is not respected? The actual API call is `pIDiaDataSource->loadDataForExe` in `pdb_file.cpp`. The value of `symStoreBuffer` appears to contain the value of `_NT_SYMBOL_PATH` even if it's not checked.

2. I'm not sure if the string value in "public store" of symbol settings is used anywhere? Although the [documentation](https://milostosic.github.io/MTuner/user_interface/main_menu/debug_symbols/) is unclear. 

I expect I should be able to specify a custom symbol server by either adding it to `_NT_SYMBOL_STORE` OR putting the URL in the "Public Store" field. But maybe that's wrong? It's not clear to me how public store / local store are actually used in code.

**Comment by milostosic** [comment]
should be fixed in v4.8.3
